name: WispFireOP
version: 1.0-SNAPSHOT
main: dev.yhdiamond.wispfireop.WispFireOP
api-version: 1.16
commands:
  wispfireop:
    usage: /wispfireop <start/stop>
    description: Starts the Wisp Fire Drops OP Items challenge